-- CreateTable
CREATE TABLE "HouseProject" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "projectId" TEXT NOT NULL,
    "websiteSlug" TEXT NOT NULL,
    "displayName" TEXT NOT NULL,
    "nameAliasesJson" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "series" TEXT,
    "sourceUrl" TEXT NOT NULL,
    "catalogUrl" TEXT,
    "snapshotDate" TEXT NOT NULL,
    "advertisedAreaM2" REAL,
    "areaDefinition" TEXT,
    "ceilingHeightM" REAL,
    "roofText" TEXT,
    "roofFamilyHint" TEXT,
    "bedroomsCount" INTEGER,
    "bathroomsCount" INTEGER,
    "featureLinesJson" TEXT NOT NULL,
    "floorPlanFile" TEXT,
    "floorPlanSourceUrl" TEXT,
    "floorPlanSha256" TEXT,
    "floorPlanReviewStatus" TEXT NOT NULL,
    "dimensionedEnvelopeMmJson" TEXT,
    "envelopeIsFullFootprint" BOOLEAN NOT NULL DEFAULT false,
    "enclosedBodyMmJson" TEXT,
    "enclosedBodyGrossAreaM2" REAL,
    "dimensionsNotes" TEXT,
    "roomsJson" TEXT NOT NULL,
    "outdoorZonesJson" TEXT NOT NULL,
    "labeledIndoorAreaSumM2" REAL,
    "labeledOutdoorAreaSumM2" REAL,
    "terraceLabeledAreaM2" REAL,
    "areaUse" TEXT,
    "missingForCostingJson" TEXT NOT NULL,
    "issuesJson" TEXT NOT NULL,
    "coverImageUrl" TEXT,
    "galleryUrlsJson" TEXT NOT NULL,
    "rawJson" TEXT NOT NULL,
    "importedAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "approvedTemplateId" TEXT
);

-- CreateIndex
CREATE UNIQUE INDEX "HouseProject_projectId_key" ON "HouseProject"("projectId");
